#!/bin/bash


main()
{
    if test -z "$DIBAS_DIR"; then
        echo "Error: DIBAS_DIR environment variable not set, exiting."
        exit 1
    fi
    $DIBAS_DIR/bin/x86_64-linux/check_vegas_status > /dev/null
    if test $? -ne 0; then
        exit -1
    fi
    exit 0
}

main 
