#!/bin/bash

#set -x
# Shared memory databuffer keys. Use spaces to separate entries
DATABUFFERKEYS="0x00c62c70 0x00c62c71 0x00c62c72"

NUMACMD="numactl --membind=1"

## Remove databuffers if they exist
remove_data_buffers()
{
    clean_guppi_shmem
    clean_vegas_shmem
    #for i in $DATABUFFERKEYS; do
    #    ipcs -m | grep $i # > /dev/null
    #    if test $? -eq 0; then
    #        ipcrm -M $i
    #    fi
    #    ipcs -s | grep $i # > /dev/null
    #    if test $? -eq 0; then
    #        ipcrm -S $i
    #    fi
    #done
}

## Setup buffers for vegas_hpc_server. If any command fails return a non-zero status
vegas_hpc_setup()
{
    # remove the previous buffers (if they exist)
    remove_data_buffers

    # Set up first (GPU) data buffer
    $NUMACMD $DIBAS_DIR/bin/x86_64-linux/check_vegas_databuf -c -i1 -n32 -s32768 -t1 >& /dev/null
    if test $? -ne 0; then
        exit -1
    fi
    # Set up second (CPU_ACCUM) data buffer
    $NUMACMD $DIBAS_DIR/bin/x86_64-linux/check_vegas_databuf -c -i2 -n32 -s32768 -t2 >& /dev/null
    if test $? -ne 0; then
        exit -1
    fi
    # Set up third (DISK) data buffer
    $NUMACMD $DIBAS_DIR/bin/x86_64-linux/check_vegas_databuf -c -i3 -n24 -s16384 -t3 >& /dev/null
    if test $? -ne 0; then
        exit -1
    fi
    exit 0
}

guppi_hpc_setup()
{
    # remove the previous buffers (if they exist)
    remove_data_buffers

    # Set up first (NET) data buffer
    $NUMACMD $DIBAS_DIR/bin/x86_64-linux/check_guppi_databuf -c -i1 -n8 -s128  >& /dev/null
    if test $? -ne 0; then
        exit -1
    fi
    # Set up second (GPU) data buffer
    $NUMACMD $DIBAS_DIR/bin/x86_64-linux/check_guppi_databuf -c -i2 -n8 -s256  >& /dev/null
    if test $? -ne 0; then
        exit -1
    fi
    exit 0
}


main()
{
    if test -z "$DIBAS_DIR"; then
        echo "Error: DIBAS_DIR environment variable not set, exiting."
        exit 1
    fi
    case "$1" in 
    vegas_*)
        vegas_hpc_setup
    ;;
    guppi_*)
        guppi_hpc_setup
    ;;
    *)
        echo "Command "$1" not understood"
        exit -1
    ;;
    esac
}

main "$1"
