#!/bin/bash
set +x

if test -z "$1"; then
    echo "Usage: $0 new_version";
    exit;
fi

if test -z "$DIBAS_DIR"; then
    echo "Environment variable DIBAS_DIR must be set. Try: source dibas.bash"
    echo "Version not changed"
    exit
fi
export DIBAS_VERSIONS_ROOT=$DIBAS_DIR/versions
cd $DIBAS_DIR

if test ! -e $DIBAS_VERSIONS_ROOT/$1; then
    echo "$DIBAS_VERSIONS_ROOT/$1 does not exist!"
    echo "Version not changed";
    exit;
fi

rm -f bin exec lib apps
ln -s $DIBAS_VERSIONS_ROOT/$1/bin bin
ln -s $DIBAS_VERSIONS_ROOT/$1/lib lib
ln -s $DIBAS_VERSIONS_ROOT/$1/exec exec
ln -s $DIBAS_VERSIONS_ROOT/$1/apps apps
ls -ld bin lib exec apps 

echo "Switched dibas software to $1"
